mark SlicerIGT extension
SlicerIGT/SlicerIGT pull request #216
Opened 2023-08-16 16:42 UTC by idrissa10

mark SlicerIGT extension for Slicer Internationalization

2023-08-17 07:32 UTC, lassoan requested changes
Thank you for working on this. I've found a couple of issues that are repeated in many places in the code. Please fix them and let me know when it's done so that I can review again.

2023-08-17 07:32 UTC, lassoan commented on BreachWarning/qSlicerBreachWarningModule.cxx
> +  return SlicerBreachWarningModule::tr("This module can alert the user by color change and sound signal if a tool enters a restricted area."
QObject-based classes should have a static `tr()` method that can be used. Why did you need to add the `SlicerBreachWarningModule::` namespace? What is `SlicerBreachWarningModule` namespace anyway (it does not seem to mach any existing class name)?

2023-08-17 07:32 UTC, lassoan commented on BreachWarning/qSlicerBreachWarningModule.cxx
> +  return SlicerBreachWarningModule::tr("This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)");
same as previous

2023-08-17 07:32 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModule.cxx
> +  return qSlicerCollectPointsModule::tr("Record motion trajectory of a tracked tool into markups fiducial list, markups curve, or model node."
Would `tr` be enough instead of `qSlicerCollectPointsModule::tr`?

2023-08-17 07:32 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModule.cxx
> +  return qSlicerCollectPointsModule::tr("This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)");
Would `tr` be enough instead of `qSlicerCollectPointsModule::tr`?

2023-08-17 07:32 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> +  d->OutputDeleteMenu = new QMenu( qSlicerCollectPointsModuleWidget::tr("Delete options") , d->OutputDeleteButton );
Would `tr` be enough instead of `qSlicerCollectPointsModule::tr`?

2023-08-17 07:32 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> +    d->CollectButton->setText( qSlicerCollectPointsModuleWidget::tr("Auto-Collect") );
Would `tr` be enough instead of `qSlicerCollectPointsModule::tr`?

2023-08-17 07:32 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> +    d->CollectButton->setText( qSlicerCollectPointsModuleWidget::tr("Collect") );
Would `tr` be enough instead of `qSlicerCollectPointsModule::tr`?

2023-08-17 07:32 UTC, lassoan commented on CreateModels/qSlicerCreateModelsModule.cxx
> +  return qSlicerCreateModelsModule::tr("Module for creating simple shapes, such as sphere, cylinder, prism, needle, and coordinate system axes."
`tr` should be sufficient, except in special cases. Please read https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md thoroughly and review all similar cases.

2023-08-17 07:32 UTC, lassoan commented on FiducialRegistrationWizard/qSlicerFiducialRegistrationWizardModuleWidget.cxx
> +  d->PointMatchingComboBox->setItemData( 0, "Point indices in the \"From\" list match those in the \"To\" list.", Qt::ToolTipRole );
This needs to be translated. Why have you removed `tr`?

2023-08-17 07:32 UTC, lassoan commented on FiducialsToModelRegistration/FiducialsToModelRegistration.py
> +    fiducialWarningLabel = qt.QLabel_(("Note: Parent transforms of fiducials are not used. Fiducials should be defined in the coordinate system that is being registered."))
Syntax error.

2023-08-17 07:32 UTC, lassoan commented on FiducialsToModelRegistration/FiducialsToModelRegistration.py
> +    self.inputFiducialSelector.setToolTip_(("Pick the input fiducial list for the algorithm."))
Syntax error.

2023-08-17 07:32 UTC, lassoan commented on FiducialsToModelRegistration/FiducialsToModelRegistration.py
> +    parametersFormLayout.addRow_(("Input fiducials: ", self.inputFiducialSelector))
Syntax error.

2023-08-17 07:32 UTC, lassoan commented on FiducialsToModelRegistration/FiducialsToModelRegistration.py
> +    self.inputModelSelector.setToolTip_(("Pick the input model for the algorithm."))
Syntax error.

2023-08-17 14:25 UTC, idrissa10 commented
Ok, thank you for the feedback.

Le jeu. 17 août 2023 à 07:32, Andras Lasso ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Thank you for working on this. I've found a couple of issues that are
> repeated in many places in the code. Please fix them and let me know when
> it's done so that I can review again.
> ------------------------------
>
> In BreachWarning/qSlicerBreachWarningModule.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296782123>:
>
> > @@ -101,15 +101,15 @@ qSlicerBreachWarningModule::~qSlicerBreachWarningModule()
>  //-----------------------------------------------------------------------------
>  QString qSlicerBreachWarningModule::helpText()const
>  {
> -  return "This module can alert the user by color change and sound signal if a tool enters a restricted area."
> +  return SlicerBreachWarningModule::tr("This module can alert the user by color change and sound signal if a tool enters a restricted area."
>
> QObject-based classes should have a static tr() method that can be used.
> Why did you need to add the SlicerBreachWarningModule:: namespace? What
> is SlicerBreachWarningModule namespace anyway (it does not seem to mach
> any existing class name)?
> ------------------------------
>
> In BreachWarning/qSlicerBreachWarningModule.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296782539>:
>
> >  }
>
>  //-----------------------------------------------------------------------------
>  QString qSlicerBreachWarningModule::acknowledgementText()const
>  {
> -  return "This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)";
> +  return SlicerBreachWarningModule::tr("This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)");
>
> same as previous
> ------------------------------
>
> In CollectPoints/qSlicerCollectPointsModule.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296783206>:
>
> > @@ -71,14 +71,14 @@ qSlicerCollectPointsModule::~qSlicerCollectPointsModule()
>  //-----------------------------------------------------------------------------
>  QString qSlicerCollectPointsModule::helpText()const
>  {
> -  return "Record motion trajectory of a tracked tool into markups fiducial list, markups curve, or model node."
> -    " For more information, visit <a href='https://github.com/SlicerIGT/SlicerIGT/#user-documentation'>SlicerIGT project website</a>.";
> +  return qSlicerCollectPointsModule::tr("Record motion trajectory of a tracked tool into markups fiducial list, markups curve, or model node."
>
> Would tr be enough instead of qSlicerCollectPointsModule::tr?
> ------------------------------
>
> In CollectPoints/qSlicerCollectPointsModule.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296783389>:
>
> >  }
>
>  //-----------------------------------------------------------------------------
>  QString qSlicerCollectPointsModule::acknowledgementText()const
>  {
> -  return "This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)";
> +  return qSlicerCollectPointsModule::tr("This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)");
>
> Would tr be enough instead of qSlicerCollectPointsModule::tr?
> ------------------------------
>
> In CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296783557>:
>
> > @@ -94,7 +94,7 @@ void qSlicerCollectPointsModuleWidget::setup()
>    connect( d->OutputNodeComboBox, SIGNAL( nodeAddedByUser( vtkMRMLNode* ) ), this, SLOT( onOutputNodeAdded( vtkMRMLNode* ) ) );
>    connect( d->OutputColorButton, SIGNAL( colorChanged( QColor ) ), this, SLOT( onColorButtonChanged( QColor ) ) );
>    connect( d->OutputDeleteButton, SIGNAL( clicked() ), this, SLOT( onDeleteButtonClicked() ) );
> -  d->OutputDeleteMenu = new QMenu(tr( "Delete options" ), d->OutputDeleteButton );
> +  d->OutputDeleteMenu = new QMenu( qSlicerCollectPointsModuleWidget::tr("Delete options") , d->OutputDeleteButton );
>
> Would tr be enough instead of qSlicerCollectPointsModule::tr?
> ------------------------------
>
> In CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296783692>:
>
> > @@ -518,13 +518,13 @@ void qSlicerCollectPointsModuleWidget::updateGUIFromMRML()
>    d->CollectButton->setEnabled( readyToCollect );
>    if ( collectPointsNode->GetCollectMode() == vtkMRMLCollectPointsNode::Automatic )
>    {
> -    d->CollectButton->setText( tr( "Auto-Collect" ) );
> +    d->CollectButton->setText( qSlicerCollectPointsModuleWidget::tr("Auto-Collect") );
>
> Would tr be enough instead of qSlicerCollectPointsModule::tr?
> ------------------------------
>
> In CollectPoints/qSlicerCollectPointsModuleWidget.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296783849>:
>
> >      d->CollectButton->setCheckable( true );
>      d->CollectButton->setChecked( true );
>    }
>    else
>    {
> -    d->CollectButton->setText( tr( "Collect" ) );
> +    d->CollectButton->setText( qSlicerCollectPointsModuleWidget::tr("Collect") );
>
> Would tr be enough instead of qSlicerCollectPointsModule::tr?
> ------------------------------
>
> In CreateModels/qSlicerCreateModelsModule.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296786880>:
>
> > @@ -65,14 +65,14 @@ qSlicerCreateModelsModule::~qSlicerCreateModelsModule()
>  //-----------------------------------------------------------------------------
>  QString qSlicerCreateModelsModule::helpText()const
>  {
> -  return "Module for creating simple shapes, such as sphere, cylinder, prism, needle, and coordinate system axes."
> -    "For help on how to use this module visit: <a href='http://www.slicerigt.org'>SlicerIGT website</a>.";
> +  return qSlicerCreateModelsModule::tr("Module for creating simple shapes, such as sphere, cylinder, prism, needle, and coordinate system axes."
>
> tr should be sufficient, except in special cases. Please read
> https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md
> thoroughly and review all similar cases.
> ------------------------------
>
> In
> FiducialRegistrationWizard/qSlicerFiducialRegistrationWizardModuleWidget.cxx
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296788139>:
>
> > @@ -209,9 +209,9 @@ void qSlicerFiducialRegistrationWizardModuleWidget::setup()
>
>    // Setup PointMatching ComboBox options
>    d->PointMatchingComboBox->addItem( tr( vtkMRMLFiducialRegistrationWizardNode::PointMatchingAsString( vtkMRMLFiducialRegistrationWizardNode::POINT_MATCHING_MANUAL ).c_str() ) );
> -  d->PointMatchingComboBox->setItemData( 0, tr( "Point indices in the \"From\" list match those in the \"To\" list." ), Qt::ToolTipRole );
> -  d->PointMatchingComboBox->addItem( tr( vtkMRMLFiducialRegistrationWizardNode::PointMatchingAsString( vtkMRMLFiducialRegistrationWizardNode::POINT_MATCHING_AUTOMATIC ).c_str() ) );
> -  d->PointMatchingComboBox->setItemData( 1, tr( "EXPERIMENTAL. Point pairing between the two lists will be computed automatically. This feature is intended only for rigid and similarity transforms." ), Qt::ToolTipRole );
> +  d->PointMatchingComboBox->setItemData( 0, "Point indices in the \"From\" list match those in the \"To\" list.", Qt::ToolTipRole );
>
> This needs to be translated. Why have you removed tr?
> ------------------------------
>
> In FiducialsToModelRegistration/FiducialsToModelRegistration.py
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1296789249>:
>
> > @@ -48,7 +48,7 @@ def setup(self):
>      #
>      # input fiducial list selector
>      #
> -    fiducialWarningLabel = qt.QLabel("Note: Parent transforms of [...]

2023-08-30 13:22 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModule.cxx
> +  return QStringList() << tr("IGT");
category is special case

2023-08-30 13:23 UTC, lassoan commented on CollectPoints/qSlicerCollectPointsModule.cxx
> +  return tr("This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)tr(");
syntax

2023-12-06 13:46 UTC, lassoan commented on FiducialRegistrationWizard/qSlicerFiducialRegistrationWizardModuleWidget.cxx
> +  correspondingFiducialString << qSlicerFiducialRegistrationWizardModuleWidget::tr("Place fiducial ");
This needs to be changed so that a complete sentence is translated, not just fragments. Something like `tr("Place fiducial (corresponding to %1")`

2024-01-24 13:48 UTC, lassoan reviewed
It is getting close, please address the inline comments.

2024-01-24 13:48 UTC, lassoan commented on BreachWarning/Resources/qSlicerBreachWarningModule_rc.py
> +# Resource object code (Python 3)
This entire file needs to be removed. It is some garbage that PySide6 generated. We don't use PySide.

2024-01-24 13:48 UTC, lassoan commented on CollectPoints/Resources/qSlicerCollectPointsModule_rc.py
> +# Resource object code (Python 3)
remove the file

2024-01-24 13:48 UTC, lassoan commented on CreateModels/Resources/qSlicerCreateModelsModule_rc.py
> +# Resource object code (Python 3)
Remove all these garbage *_rc.py files.

2024-01-25 16:56 UTC, idrissa10 commented
Hi Andras,
all *_rc.py files are removed. THanks to check.

Best regards

 Idrissa



Le mer. 24 janv. 2024 à 13:48, Andras Lasso ***@***.***> a
écrit :

> ***@***.**** commented on this pull request.
>
> It is getting close, please address the inline comments.
> ------------------------------
>
> In BreachWarning/Resources/qSlicerBreachWarningModule_rc.py
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1464931855>:
>
> > @@ -0,0 +1,78 @@
> +# Resource object code (Python 3)
>
> This entire file needs to be removed. It is some garbage that PySide6
> generated. We don't use PySide.
> ------------------------------
>
> In CollectPoints/Resources/qSlicerCollectPointsModule_rc.py
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1464932496>:
>
> > @@ -0,0 +1,382 @@
> +# Resource object code (Python 3)
>
> remove the file
> ------------------------------
>
> In CreateModels/Resources/qSlicerCreateModelsModule_rc.py
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#discussion_r1464933037>:
>
> > @@ -0,0 +1,112 @@
> +# Resource object code (Python 3)
>
> Remove all these garbage *_rc.py files.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SlicerIGT/SlicerIGT/pull/216#pullrequestreview-1841405047>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJKZBM6H7FXR2O725URQGVTYQEGLLAVCNFSM6AAAAAA3SZ2X6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBRGQYDKMBUG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-23 06:41 UTC, lassoan commented
I've fixed up all the remaining issues and will merge now.

2024-06-23 06:41 UTC, lassoan approved these changes

2024-06-23 06:41 UTC, merged